version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: profact-simulated-practical-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: profact_simulated_practical_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d # 初期化SQLの配置場所
      - ./data:/var/lib/mysql
